# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: make application-database.yml
        run: |
          cd ./src/main/resources
          
          touch ./application-database.yml
          
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml

        shell: bash

      - name: make test application-database.yml
        run: |
          cd ./src/test/resources
          
          touch ./application-database.yml
          
          echo "${{ secrets.DATABASE }}" >> ./application-database.yml
        shell: bash

      - name: make application-api.yml
        run: |
          cd ./src/main/resources
          
          touch ./application-api.yml
          
          echo "${{ secrets.API }}" >> ./application-api.yml
        

        shell: bash

      - name: make test application-api.yml
        run: |
          cd ./src/test/resources
          
          touch ./application-api.yml
          
          echo "${{ secrets.API }}" >> ./application-api.yml

        shell: bash

      - name: make application-secret.yml
        run: |
          cd ./src/main/resources
          
          touch ./application-secret.yml
          
          echo "${{ secrets.SECRET_KEY }}" >> ./application-secret.yml
        

        shell: bash

      - name: make test application-secret.yml
        run: |
          cd ./src/test/resources
          
          touch ./application-secret.yml
          
          echo "${{ secrets.SECRET_KEY }}" >> ./application-secret.yml

        shell: bash

      # - name: Build with Gradle Wrapper
      #   run: ./gradlew build

      # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
      # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
      #
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      #   with:
      #     gradle-version: '8.5'
      #
      - name: Build with Gradle 8.5
        run: gradle build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Make dir
        run: mkdir cicd

      - name: Copy jar
        run: cp ./build/libs/*.jar ./cicd

      - name: Copy appspec
        run: cp ./appspec.yml ./cicd

      - name: Copy script
        run: cp ./scripts/deploy.sh ./cicd

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://woojjam/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name woojjam-code-deploy-app --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name woojjam-code-deploy-group --s3-location bucket=woojjam,bundleType=zip,key=$GITHUB_SHA.zip


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
